name: Build

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows",
            os: windows-latest,
            generator: "Visual Studio 17 2022",
            target: "ALL_BUILD"
          }
        - {
            name: "Linux",
            os: ubuntu-latest,
            generator: "Unix Makefiles",
            target: "all"
          }

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Folder
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure cmake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: cmake -G "${{ matrix.config.generator }}" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGAME_VERSION=latest -DWITH_ENCRYPTION=ON -S $GITHUB_WORKSPACE -B .

      - name: Build
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --config $BUILD_TYPE --parallel 2 --target ${{ matrix.config.target }}

      - name: Upload binary to Release (Ubuntu)
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/bin/sniffcraft
          asset_name: sniffcraft-linux
          tag: latest
          overwrite: true
          prerelease: false

      - name: Upload binary to Release (Windows)
        if: ${{ matrix.config.os == 'windows-latest' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/bin/sniffcraft.exe
          asset_name: sniffcraft-windows.exe
          tag: latest
          overwrite: true
          prerelease: false

  update_latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update Latest Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
