name: Build

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows",
            os: windows-latest,
            generator: "Visual Studio 17 2022",
            target: "ALL_BUILD"
          }
        - {
            name: "Linux",
            os: ubuntu-latest,
            generator: "Unix Makefiles",
            target: "all"
          }

    steps:
      - uses: actions/checkout@v3

      - name: Create build folder
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure cmake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: >
          cmake -G "${{ matrix.config.generator }}"
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DGAME_VERSION=latest
          -DSNIFFCRAFT_WITH_ENCRYPTION=ON
          -DSNIFFCRAFT_FORCE_LOCAL_ZLIB=ON
          -DSNIFFCRAFT_FORCE_LOCAL_OPENSSL=ON
          -S $GITHUB_WORKSPACE
          -B .

      - name: Build
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --config $BUILD_TYPE --parallel 2 --target ${{ matrix.config.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sniffcraft-${{ matrix.config.name }}
          path: ${{ github.workspace }}/bin/sniffcraft*
          retention-days: 1

      - name: Upload version artifact
        if: ${{ matrix.config.name == 'Linux' }}
        uses: actions/upload-artifact@v3
        with:
          name: MC-version
          path: ${{ runner.workspace }}/build/version.txt
          retention-days: 1

      - name: Retrieve MC game version
        if: ${{ matrix.config.name == 'Linux' }}
        id: mc-version
        uses: juliangruber/read-file-action@v1
        with:
          path:
            ${{ runner.workspace }}/build/version.txt

      - name: Create release note
        if: ${{ matrix.config.name == 'Linux' }}
        run: |
            echo Automatically generated binaries with the latest version of the code for Minecraft ${{ steps.mc-version.outputs.content }}. > release_note.txt
            echo -en '\n' >> release_note.txt
            echo "Examples of conf files can be found [here](https://github.com/${{ github.repository }}/tree/master/conf)." >> release_note.txt
            echo -en '\n' >> release_note.txt
            echo "💡 If you need binaries for a previous version of Minecraft, you can open [an issue using this link](https://github.com/${{ github.repository }}/issues/new?assignees=&labels=version+request&template=version-request.yml&title=%5BVersion+request%5D) and it will be automagically generated for you in a few minutes." >> release_note.txt
            echo -en '\n' >> release_note.txt
            echo **Changes:** >> release_note.txt

      - name: Append git commits
        if: ${{ matrix.config.name == 'Linux' }}
        run: git log latest..HEAD --oneline --no-merges >> release_note.txt

      - name: Upload release note
        if: ${{ matrix.config.name == 'Linux' }}
        uses: actions/upload-artifact@v3
        with:
          name: release_note
          path: release_note.txt
          retention-days: 1

  update_latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v3
        with:
          name: MC-version
          path: version

      - name: Retrieve MC game version
        id: mc-version
        uses: juliangruber/read-file-action@v1
        with:
          path:
            version/version.txt

      - name: Download release note
        uses: actions/download-artifact@v3
        with:
          name: release_note
          path: release_note

      - name: Remove old latest release
        uses: cb80/delrel@latest
        with:
          tag: latest

      - name: Update latest tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new latest release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_note/release_note.txt            
          draft: false
          prerelease: false
          name: Latest
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: sniffcraft-Linux
          path: linux

      - name: Upload Linux file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux/sniffcraft
          asset_name: sniffcraft-linux-${{ steps.mc-version.outputs.content }}
          tag: latest

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: sniffcraft-Windows
          path: windows

      - name: Upload Windows file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: windows/sniffcraft.exe
          asset_name: sniffcraft-windows-${{ steps.mc-version.outputs.content }}.exe
          tag: latest
