name: Manual Build

on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: 'Minecraft Version'
        required: true
        default: 'latest'
      issue:
        description: 'URL of the issue requesting this build'
        required: false
        default: ''

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows",
            os: windows-latest,
            generator: "Visual Studio 17 2022",
            target: "ALL_BUILD"
          }
        - {
            name: "Linux",
            os: ubuntu-latest,
            generator: "Unix Makefiles",
            target: "all"
          }

    steps:
      - uses: actions/checkout@v3

      - name: Create build folder
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure cmake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: >
          cmake -G "${{ matrix.config.generator }}"
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DGAME_VERSION=${{ github.event.inputs.minecraft_version }}
          -DSNIFFCRAFT_WITH_ENCRYPTION=ON
          -DSNIFFCRAFT_FORCE_LOCAL_ZLIB=ON
          -DSNIFFCRAFT_FORCE_LOCAL_OPENSSL=ON
          -S $GITHUB_WORKSPACE
          -B .

      - name: Build all
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --config $BUILD_TYPE --parallel 2 --target ${{ matrix.config.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sniffcraft-${{ matrix.config.name }}
          path: ${{ github.workspace }}/bin/sniffcraft*
          retention-days: 1

  update_latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: sniffcraft-Linux
          path: linux

      - name: Upload Linux file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux/sniffcraft
          asset_name: sniffcraft-linux-${{ github.event.inputs.minecraft_version }}
          tag: latest

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: sniffcraft-Windows
          path: windows

      - name: Upload Windows file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: windows/sniffcraft.exe
          asset_name: sniffcraft-windows-${{ github.event.inputs.minecraft_version }}.exe
          tag: latest

      - name: Comment on associated issue
        if: ${{ github.event.inputs.issue }}
        run: |
          echo "New binaries available in the [latest release](https://github.com/${{ github.repository }}/releases/tag/latest) for version ${{ github.event.inputs.minecraft_version }}" > body.txt
          echo -en '\n' >> body.txt
          echo You can now close this issue. Feel free to reopen at anytime if you need an updated build for the same version. >> body.txt
          gh issue comment ${{ github.event.inputs.issue }} --repo ${{ github.repository }} --body-file body.txt
        env:
          GH_TOKEN: ${{ github.token }}
